FROM node:8.12.0

RUN apt-get update

#get & install Ds-server
RUN mkdir /home/ds-cms
WORKDIR /home/ds-cms

COPY ./cms ./cms
COPY ./envs ./envs
COPY ./uploads ./uploads
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm i

ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}

ARG BUILD_ENV
ENV BUILD_ENV ${BUILD_ENV}

RUN npm run cms-client:build

EXPOSE 443 3001 8080

CMD ["npm", "run", "cms"]

